name:                llvm-hs-tutor
version:             12.0.0
github:              "llvm-hs/llvm-hs-tutor"
license:             BSD3
author:              "Andrew Anderson"
maintainer:          "aanderso@tcd.ie"
copyright:           "2021 Andrew Anderson"

extra-source-files:
- README.md

synopsis:            Haskell version of llvm-tutor
category:            Compilers

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/llvm-hs-tutor#readme>

executables:
  helloworld:
    main:                HelloWorld.hs
    source-dirs:         app
    dependencies:
    - base >= 4.7 && < 5
    - mtl
    - bytestring
    - llvm-hs       >= 12 && < 13
    - llvm-hs-pure  >= 12 && < 13
